# -*- coding: utf-8 -*-
"""4- Polynomial Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-pRGh0uw9u_pmewTFjlYZRHcWPQzDdY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
Y = dataset.iloc[:, -1].values

print(X)
print(Y)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, Y)

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, Y)

plt.scatter(X, Y, color='red')
plt.plot(X, lin_reg.predict(X), color = 'blue')
plt.title("Truth or bluff (Linear regression)")
plt.xlabel("position level")
plt.ylabel("salaries")
plt.show()

plt.scatter(X, Y, color='red')
plt.plot(X, lin_reg_2.predict(X_poly), color = 'blue')
plt.title("Truth or bluff (Polynomial regression)")
plt.xlabel("position level")
plt.ylabel("salaries")
plt.show()

poly_reg_2 = PolynomialFeatures(degree = 4)
X_poly_2 = poly_reg_2.fit_transform(X)
lin_reg_3 = LinearRegression()
lin_reg_3.fit(X_poly_2, Y)

plt.scatter(X, Y, color='red')
plt.plot(X, lin_reg_3.predict(X_poly_2), color = 'blue')
plt.title("Truth or bluff (Polynomial regression)")
plt.xlabel("position level")
plt.ylabel("salaries")
plt.show()

lin_reg.predict([[6.5]])

lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))